### PR TITLE
Replace vinyl fs by fast glob

### PR DESCRIPTION
**Pull request by hugobessa**
Vinyl-fs didn't have any updates since a few years ago and the version of glob-parent they use has vulnerabilities reported by DependaBot. So I'd like to propose replacing it with [fast-glob](https://www.npmjs.com/package/fast-glob) instead.

### CODE REVIEW

**Comment by hugobessa** [comment]
@mdeanjones my tests are passing locally, but apparently, they're all failing in TravisCI. Do you have any hint on what may be going on?

**Comment by hugobessa** [comment]
Actually, it is failing on Github Actions, not Travis. I've got confused because I saw the config file for Travis. I suspect this is related to the node engine.

**Comment by hugobessa** [comment]
I took the liberty, to limit the node engines to >=14. Feel free to let me know if that's not reasonable. The tests are passing on CI now.

**Comment by mdeanjones** [comment]
Node 14 is the current maintenance, with 16 being active. Provided its a major version bump I can't find too much justification to not modernize.

**Pull request merged**
