### PR TITLE
Support node 7 & 8

### PR DESCRIPTION
**Pull request by hsiliev**

### CODE REVIEW

**Comment by mweibel** [comment]
thanks! would you be so kind to update the build matrix in travis CI too? 
I'd even go so far as doing the requirements `>= 4` and adjust the travis-CI build matrix that way too.

**Comment by mweibel** [comment]
ah, spoke too soon 🙂 thanks!

**Comment by hsiliev** [comment]
When can we expect the next release? Can we do something to help with that?

**Comment by mweibel** [comment]
Given that semantic release still works it should be done with the next build.. will need to check though. Will give an update afterwards.

**Comment by mweibel** [comment]
@hsiliev had to update semantic-release etc. and version 2.0.0 has been released on NPM now.

**Comment by hsiliev** [comment]
Thanks a lot

**Pull request merged**
